---
commonOverlays:
  - name: "inject the platform purpose label"
    query: "$"
    action: merge
    value:
      metadata:
        labels:
          app.kubernetes.io/name: external-dns
          platform.kubernetes.io/purpose: dns-updates
      spec:
        template:
          metadata:
            labels:
              app.kubernetes.io/name: external-dns
              platform.kubernetes.io/purpose: dns-updates
    documentQuery:
      - conditions:
          - query: $[?($.kind == "Deployment")]

yamlFiles:
  - name: "external-dns deployments"
    path: "../../vendor/external-dns-deployment.yaml"
    outputPath: "ingress/external-dns/active-directory-deployment.yaml"
    overlays:
      - name: "update deployment spec"
        query: $
        value:
          metadata:
            name: "{{ .names.active_directory }}"
            namespace: "{{ .namespace }}"
          spec:
            replicas: !!int {{ .replicas }}
            template:
              spec:
                securityContext:
                  fsGroup: 1001
                  runAsUser: 1001
                  runAsGroup: 1001
                  runAsNonRoot: true
                volumes:
                  - name:  external-dns-active-directory-kerberos
                    configMap:
                      defaultMode: 420
                      name: external-dns-active-directory-kerberos
                nodeSelector:
                  kubernetes.io/os: linux
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                          topologyKey: kubernetes.io/hostname
                          labelSelector:
                            matchExpressions:
                              - key: app.kubernetes.io/name
                                operator: In
                                values:
                                  - "{{ .names.active_directory }}"

      - name: "update container spec"
        query: spec.template.spec.containers[*]
        value:
          envFrom:
            - secretRef:
                name: external-dns-active-directory
          image: "{{ .image }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "{{ .resources.requests.cpu }}"
              memory: "{{ .resources.requests.memory }}"
            limits:
              cpu: "{{ .resources.limits.cpu }}"
              memory: "{{ .resources.limits.memory }}"
          volumeMounts:
            - name: external-dns-active-directory-kerberos
              subPath: krb5.conf
              mountPath: /etc/krb5.conf

      - name: "replace container args for active directory"
        query: spec.template.spec.containers[*].args
        action: replace
        onMissing:
          action: inject
        value:
          - --source=service
          - --source=ingress
          - --registry=txt
          - --txt-owner-id=$(EXTERNAL_DNS_OWNER_PREFIX)
          - --txt-prefix=$(EXTERNAL_DNS_OWNER_PREFIX)
          - --provider=rfc2136
          - --rfc2136-gss-tsig
          - --rfc2136-tsig-axfr
          - --rfc2136-host=$(ACTIVE_DIRECTORY_HOSTNAME)
          - --rfc2136-port=53
          - --rfc2136-kerberos-username=$(ACTIVE_DIRECTORY_USERNAME)
          - --rfc2136-kerberos-password=$(ACTIVE_DIRECTORY_PASSWORD)
          - --rfc2136-kerberos-realm=$(ACTIVE_DIRECTORY_REALM)
          - --rfc2136-zone=$(ACTIVE_DIRECTORY_DOMAIN)
          - --domain-filter=$(ACTIVE_DIRECTORY_DOMAIN)
          - --policy=sync
