---
commonOverlays: []
yamlFiles:
  - name: "external-dns config"
    path: "../../static/active-directory-config.yaml"
    outputPath: "ingress/external-dns/active-directory-config.yaml"
    overlays:
      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"
        onMissing:
          action: inject
