---
commonOverlays:
  - name: "inject the platform purpose label"
    query: "$"
    action: merge
    value:
      metadata:
        labels:
          app: external-dns-route53
          app.kubernetes.io/name: external-dns-route53
          app.kubernetes.io/instance: external-dns
          platform.kubernetes.io/purpose: dns-updates
      spec:
        selector:
          matchLabels:
            app: external-dns-route53
        template:
          metadata:
            labels:
              app.kubernetes.io/name: external-dns-route53
              app.kubernetes.io/instance: external-dns
              platform.kubernetes.io/purpose: dns-updates
    documentQuery:
      - conditions:
          - query: $[?($.kind == "Deployment")]

yamlFiles:
  - name: "external-dns deployments"
    path: "../../vendor/external-dns-deployment.yaml"
    outputPath: "ingress/external-dns/route53-deployment.yaml"
    overlays:
      - name: "update deployment spec"
        query: $
        value:
          metadata:
            name: "{{ .names.active_directory }}"
            namespace: "{{ .namespace }}"
          spec:
            replicas: !!int {{ .replicas }}
            template:
              spec:
                securityContext:
                  fsGroup: 1001
                  runAsUser: 1001
                  runAsGroup: 1001
                  runAsNonRoot: true
                nodeSelector:
                  kubernetes.io/os: linux
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                          topologyKey: kubernetes.io/hostname
                          labelSelector:
                            matchExpressions:
                              - key: app.kubernetes.io/name
                                operator: In
                                values:
                                  - "{{ .names.active_directory }}"

      - name: "update container spec"
        query: spec.template.spec.containers[*]
        value:
          envFrom:
            - secretRef:
                name: external-dns-route53
          image: "{{ .image }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "{{ .resources.requests.cpu }}"
              memory: "{{ .resources.requests.memory }}"
            limits:
              cpu: "{{ .resources.limits.cpu }}"
              memory: "{{ .resources.limits.memory }}"

      - name: "replace container args for active directory"
        query: spec.template.spec.containers[*].args
        action: replace
        onMissing:
          action: inject
        value:
          - --source=service
          - --source=ingress
          - --registry=txt
          - --domain-filter=$(ROUTE53_DOMAIN)
          - --provider=aws
          - --policy=sync
          - --aws-zone-type=private
          - --txt-owner-id=$(EXTERNAL_DNS_OWNER_PREFIX)
          - --txt-prefix=$(EXTERNAL_DNS_OWNER_PREFIX)
          - --aws-prefer-cname
